# Generated by Django 5.2.4 on 2026-05-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownershiptransfer',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
