# Generated by Django 5.2.4 on 2026-07-28 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_last_name_user_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpsdevice',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='owner',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='farm_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='farm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owner',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='primary_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_owner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='owner',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='total_animals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='total_gps_devices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='owner_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='owner',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'FARMER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
