import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:provider/provider.dart';
import '../utils/constants.dart';

class LanguageService extends ChangeNotifier {
  static const String defaultLanguageCode = 'en';

  Locale _currentLocale = const Locale(defaultLanguageCode);

  Locale get currentLocale => _currentLocale;

  final Map<String, Map<String, String>> _translations = {
    'en': {

      'app_name': 'Livestock Tracking System',
      'welcome': 'Welcome Back!',
      'login': 'Login',
      'register': 'Register',
      'logout': 'Logout',
      'phone_number': 'Phone Number',
      'password': 'Password',
      'full_name': 'Full Name',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'address': 'Address',
      'select_language': 'Select Language',
      'english': 'English',
      'swahili': 'Kiswahili',
      'login_success': 'Login Successful',
      'register_success': 'Registration Successful',
      'login_error': 'Invalid phone number or password',
      'register_error': 'Registration failed',
      'network_error': 'Network error',
      'retry': 'Retry',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'ok': 'OK',
      'close': 'Close',
      'search': 'Search...',
      'loading': 'Loading...',
      'optional': 'Optional',
      'email': 'Email',
      'language': 'Language',
      'location': 'Location',
      'create_account': 'Create Account',
      'login_to_continue': 'Login to continue',
      'confirm_logout': 'Confirm Logout',
      'confirm_logout_message': 'Are you sure you want to logout?',
      'user': 'User',
      'full_name_required': 'Full name is required',
      'animal_name_required': 'Please enter animal name',
      'animal_added_success': 'Animal added successfully',
      'animal_add_failed': 'Failed to add animal',
      'image_error': 'There is a problem with the image',
      'name_error': 'Name',
      'error': 'Error',
      'phone': 'Phone',
      'not_available': 'Not available',
      'full_details': 'Full Details',
      'details': 'Details',
      'basic_information': 'Basic Information',
      'search_farmer': 'Search farmer...',
      'search_animal': 'Search animal...',
      'try_changing_search': 'Try changing your search or tap refresh',
      'try_changing_filter': 'Try changing the filter or search',
      'no_data_available': 'No data available',
      'loading_user_data': 'Loading user data...',
      'confirm_delete': 'Confirm Delete',
      'confirm_delete_record': 'Are you sure you want to delete this record?',
      'delete_transfer_confirm':
          'Are you sure you want to delete this transfer record?',
      'delete_farmer_confirm':
          'Are you sure you want to delete this farmer? This action cannot be undone. Their animals will also be deleted.',
      'farmer_updated': 'Farmer updated successfully',
      'farmer_deleted': 'Farmer deleted successfully',
      'update_failed': 'Failed to update',
      'delete_failed': 'Failed to delete',
      'transfer_deleted': 'Transfer record deleted',
      'transfer_accepted': 'Transfer accepted',
      'transfer_rejected': 'Transfer rejected',
      'request_overdue': 'Request overdue',
      'last_1_day': 'Last 1 day',
      'last_7_days': 'Last 7 days',
      'last_14_days': 'Last 14 days',
      'last_30_days': 'Last 30 days',
      'days': 'days',
      'point': 'Point',
      'legend': 'Legend',
      'click_marker_details': 'Click on markers for details',
      'click_to_view_map': 'Tap to view map',
      'animal_map': 'Animal Map',
      'center_on_animals': 'Center on Animals',
      'status_label': 'Status',
      'last_seen_location': 'Last seen location',
      'animal': 'Animal',
      'animal_number': 'Animal Number',
      'livestock_number': 'Livestock Number',
      'type': 'Type',
      'color': 'Color',
      'change_status': 'Change Status',
      'link_gps_device': 'Link GPS Device',
      'history': 'History',
      'change_picture': 'Change picture',
      'name_of_livestock': 'Name of Livestock',
      'type_of_livestock': 'Type of Livestock',
      'save_changes': 'Save Changes',
      'edit_livestock': 'Edit Livestock',
      'animal_update_success': 'Animal details updated successfully',
      'animal_update_failed': 'Failed to update animal details',
      'status_update_success': 'Status changed successfully',
      'status_update_failed': 'Failed to change status',
      'animal_delete_confirm':
          'Are you sure you want to delete this animal? This action cannot be undone.',
      'animal_deleted_success': 'Animal deleted successfully',
      'recipient_not_found':
          'The recipient you entered was not found in the system. Please ensure the phone number is correct.',
      'self_transfer_error':
          'You cannot transfer ownership to yourself. Please enter a different recipient phone number.',
      'invalid_recipient_phone': 'Recipient phone number is invalid.',
      'recipient_phone_required': 'Please enter the recipient phone number',
      'request_sent_success': 'Your request has been sent successfully',
      'transfer_details_upper': 'Transfer Details',
      'notes_optional': 'Notes (Optional)',
      'transfer_notice':
          'The recipient will be notified and has 7 days to accept the transfer.',
      'start_transfer': 'Start Transfer',
      'phone_hint': '255XXXXXXXXX or 0XXXXXXXXX',
      'passwords_do_not_match': 'Passwords do not match',
      'password_min_length': 'Password must be at least 6 characters',
      'registration_failed_try_again': 'Registration failed. Please try again.',
      'message_title_required': 'Please enter the message title',
      'message_required': 'Please enter your message',
      'broadcast_success_all': 'Message sent successfully to all farmers',
      'broadcast_header': 'Message to All Farmers',
      'broadcast_subtitle': 'Your message will reach all registered farmers',
      'broadcast_description':
          'This message will be sent to all farmers registered in the system.',
      'message_title': 'Message Title',
      'message_title_hint': 'Example: IMPORTANT NOTICE FOR FARMERS',
      'your_message': 'Your Message',
      'message_hint':
          'Write your message here...\n\nExample: Every farmer who attends the meeting on the 15th will receive modern livestock training...',
      'message_preview': 'Message Preview',
      'preview_empty': 'Your message preview will appear here',
      'send_message': 'Send Message',
      'broadcast_footer': 'The message will reach all registered farmers',
      'take_photo': 'Take Photo',
      'choose_from_gallery': 'Choose from Gallery',
      'device_id_hint': 'Example: GPS001, GPS002, etc.',
      'qr_hint': 'Scan QR code if you have one',
      'all_required_fields': 'Please fill all required fields',
      'registration_success': 'Your registration has completed successfully',
      'add_new_police_officer': 'Add New Law Enforcement Officer',
      'add_police_subtitle':
          'Fill in the details to add a law enforcement officer to the system',
      'police_added_success': 'Police officer added successfully',
      'police_add_failed': 'Failed to add police officer',
      'add_police_button': 'Add Law Enforcement officer',
      'phone_helper': 'Example: 255712345678 or 0712345678',
      'all': 'All',
      'no_animals_found': 'No animals found',
      'no_farmers_found_title': 'No farmers found',
      'name_not_available': 'Name not available',
      'phone_not_available': 'Phone not available',
      'no_animals_yet': 'No animals yet',
      'gps_device_required': 'Please enter Device ID',
      'device_not_found':
          'Device not found. Please contact the Agriculture Officer.',
      'gps_linked_success': 'GPS device linked successfully',
      'gps_link_failed': 'Failed to link device',
      'link_gps_title': 'Link GPS Device',
      'enter_gps_device_id': 'Enter the GPS tracker Device ID',
      'gps_device_help': 'The Device ID is available on your GPS tracker',
      'device_id_helper': 'Choose any Device ID such as GPS001, GPS002, GPS003',
      'qr_code_optional': 'QR Code (Optional)',
      'link_device_button': 'Link Device',

      
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'middle_name': 'Middle Name',
      'first_name_required': 'First name is required',
      'last_name_required': 'Last name is required',
      'first_name_min_length': 'First name must be at least 3 characters',
      'first_name_max_length': 'First name must be less than 10 characters',
      'first_name_letters_only': 'First name can only contain letters',
      'last_name_min_length': 'Last name must be at least 3 characters',
      'last_name_max_length': 'Last name must be less than 10 characters',
      'last_name_letters_only': 'Last name can only contain letters',
      'middle_name_min_length': 'Middle name must be at least 3 characters',
      'middle_name_max_length': 'Middle name must be less than 10 characters',
      'middle_name_letters_only': 'Middle name can only contain letters',


      'phone_required': 'Phone number is required',
      'phone_invalid_format': 'Phone number must be 9 digits',
      'phone_invalid_network':
          'Invalid network prefix. Use Vodacom, Airtel, Tigo (yas), or Halotel',

      'location_required': 'Location is required',
      'location_min_length': 'Location must be at least 3 characters',

   
      'password_required': 'Password is required',
      'password_min_length_8': 'Password must be at least 8 characters',
      'password_uppercase':
          'Password must contain at least one uppercase letter',
      'password_lowercase':
          'Password must contain at least one lowercase letter',
      'password_number': 'Password must contain at least one number',
      'password_special':
          'Password must contain at least one special character (!@#\$%^&*(),.?":{}|<>)',

      'email_invalid': 'Please enter a valid email address',

      'confirm_password_required': 'Please confirm your password',
      'password_min_hint': '8+ chars: A-Z, a-z, 0-9, !@#',

      'network_vodacom': 'Vodacom',
      'network_airtel': 'Airtel',
      'network_tigo': 'Tigo (yas)',
      'network_halotel': 'Halotel',


      'farmer_dashboard': 'Farmer Dashboard',
      'officer_dashboard': 'Officer Dashboard',
      'police_dashboard': 'Police Dashboard',
      'dashboard': 'Dashboard',
      'habari': 'Hello',

      'law_enforcement_dashboard': 'Law Enforcement Dashboard',
      'good_morning': 'Good Morning',
      'total_cases': 'Total Cases',
      'stolen_reported': 'Stolen Reported',
      'recovered': 'Recovered',
      'pending': 'Pending',
      'quick_actions': 'Quick Actions',
      'report_stolen': 'Report Stolen',
      'search_animal': 'Search Animal',
      'view_map': 'View Map',
      'recent_reports': 'Recent Reports',
      'new': 'New',
      'view_all_reports': 'View All Reports',
      'no_recent_reports': 'No recent reports',
      'animal_details': 'Animal Details',
      'last_known_location': 'Last Known Location',
      'latitude': 'Latitude',
      'longitude': 'Longitude',
      'view_on_map': 'View on Map',

    
      'total_animals': 'Total Animals',
      'active_gps': 'Active GPS',
      'unread_alerts': 'Unread Alerts',
      'stolen_animals': 'Stolen Animals',
      'stolen_animals_reported': 'Stolen Animals Reported',
      'stolen_animals_list': 'Stolen Animals List',
      'no_stolen_animals': 'No stolen animals reported',
      'total_farmers': 'Total Farmers',
      'view_all': 'View All',

      'my_animals': 'My Animals',
      'all_animals': 'All Animals',
      'add_animal': 'Add Animal',
      'animal_name': 'Animal Name',
      'animal_type': 'Animal Type',
      'animal_color': 'Animal Color',
      'cattle': 'Cattle',
      'goat': 'Goat',
      'sheep': 'Sheep',
      'other': 'Other',
      'add_photo': 'Add Photo',
      'notes': 'Notes',
      'animal_id': 'Animal ID',
      'owner': 'Owner',
      'status': 'Status',
      'update_status': 'Update Status',
      'active': 'Active',
      'sold': 'Sold',
      'slaughtered': 'Slaughtered',
      'dead': 'Dead',
      'stolen': 'Stolen',
      'no_animals': 'No animals found',
      'animals': 'Animals',
      'mark_as_active': 'Mark as Active',
      'mark_as_sold': 'Mark as Sold',
      'mark_as_slaughtered': 'Mark as Slaughtered',
      'mark_as_dead': 'Mark as Dead',
      'report_as_stolen': 'Report as Stolen',

     
      'location_history': 'Location History',
      'view_on_map': 'View on Map',
      'no_location_data': 'No location data available',
      'no_location_data_for_animal': 'No location data for this animal',
      'location_points': 'Location Points',
      'start': 'Start',
      'current': 'Current',
      'center_on_map': 'Center on Map',
      'last_seen': 'Last Seen',
      'speed': 'Speed',
      'reported_on': 'Reported On',
      'open_in_maps': 'Open in Maps',


      'transfer_ownership': 'Transfer Ownership',
      'transfer_requests': 'Transfer Requests',
      'transfer_details': 'Transfer Details',
      'recipient_phone_number': 'Recipient Phone Number',
      'initiate_transfer': 'Initiate Transfer',
      'transfer_info': 'The recipient will have 7 days to accept this transfer',
      'transfer_initiated_success': 'Transfer initiated successfully',
      'transfer_failed': 'Failed to initiate transfer',
      'no_transfers': 'No transfer history',
      'from': 'From',
      'to': 'To',
      'initiated_at': 'Initiated At',
      'confirmed_at': 'Confirmed At',
      'pending': 'Pending',
      'confirmed': 'Confirmed',
      'rejected': 'Rejected',
      'expired': 'Expired',
      'accept': 'Accept',
      'reject': 'Reject',
      'delete_record': 'Delete Record',

      'alerts': 'Alerts',
      'all_alerts': 'All Alerts',
      'no_alerts': 'No alerts',
      'mark_as_read': 'Mark as Read',
      'theft_alert': 'Theft Alert',
      'lost_animal_alert': 'Lost Animal Alert',
      'general_alert': 'General Alert',
      'new_alerts': 'New Alerts',
      'proximity_alarm_title': 'Animal distance alarm',
      'proximity_alarm_attention': 'Distance alarm needs attention',
      'proximity_alarm_message': 'These animals are more than 5m apart:',
      'proximity_alarm_location_problem':
          'Keep internet on to use the animal distance alarm.',
      'stop_alarm': 'Stop alarm',

      'reports': 'Reports',
      'generate_report': 'Generate Report',
      'population_report': 'Population Report',
      'generate_population_report_desc':
          'Generate a report showing total animals by type and status',
      'report_results': 'Report Results',
      'report_generated_success': 'Report generated successfully',
      'report_generate_failed': 'Failed to generate report',
      'animals_by_type': 'Animals by Type',
      'animals_by_status': 'Animals by Status',
      'generated_at': 'Generated at',

      'send_broadcast': 'Send Broadcast',
      'broadcast_info':
          'This message will be sent to all farmers in the system',
      'title': 'Title',
      'message': 'Message',
      'preview': 'Preview',
      'broadcast_sent_successfully': 'Broadcast sent successfully',
      'broadcast_failed': 'Failed to send broadcast',

      'farmers': 'Farmers',
      'farmers_list': 'Farmers List',
      'no_farmers_found': 'No farmers found',
      'edit_farmer': 'Edit Farmer',
      'delete_farmer': 'Delete Farmer',
      'farmer_details': 'Farmer Details',
      'joined': 'Joined',
      'joined_date': 'Joined Date',
      'role': 'Role',
      'basic_info': 'Basic Information',
      'animals_count': 'Animals',

      'profile': 'Profile',
      'my_profile': 'My Profile',
      'settings': 'Settings',

      'theft_alerts': 'Theft Alerts',
      'add_police': 'Add Police Officer',
      'police_officer': 'Police Officer',
      'work_location': 'Work Location',
      'Law_enforcement': 'Law Enforcement',

      'activity_log': 'Activity Log',
      'no_logs_found': 'No logs found',
      'activity_type': 'Activity Type',
      'description': 'Description',
      'timestamp': 'Timestamp',

      'my_animals_menu': 'My Animals',
      'add_animal_menu': 'Add Animal',
      'transfer_requests_menu': 'Transfer Requests',
      'alerts_menu': 'Alerts',
      'farmers_menu': 'Farmers',
      'all_animals_menu': 'All Animals',
      'broadcast_menu': 'Broadcast',
      'reports_menu': 'Reports',
      'activity_log_menu': 'Activity Log',
      'police_menu': 'Law Enforcement',
      'stolen_animals_menu': 'Stolen Animals',
      'theft_alerts_menu': 'Theft Alerts',
      'profile_menu': 'My Profile',
      'logout_menu': 'Logout',

      'save': 'Save',
      'edit': 'Edit',
      'delete': 'Delete',
      'update': 'Update',
      'refresh': 'Refresh',
      'back': 'Back',
      'next': 'Next',
      'submit': 'Submit',
      'continue': 'Continue',

      'family_members_menu': 'Family Members',
    },
    'sw': {
      'family_members_menu': 'Washiriki wa Familia',
      // ========== GENERAL ==========
      'app_name': 'Mfumo wa Kufuatilia Mifugo',
      'welcome': 'Karibu Tena!',
      'login': 'Ingia',
      'register': 'Jisajili',
      'logout': 'Toka',
      'phone_number': 'Namba ya Simu',
      'password': 'Nywila',
      'full_name': 'Jina Kamili',
      'confirm_password': 'Thibitisha Nywila',
      'forgot_password': 'Umesahau Nywila?',
      'dont_have_account': 'Huna akaunti?',
      'already_have_account': 'Tayari una akaunti?',
      'address': 'Eneo',
      'select_language': 'Chagua Lugha',
      'english': 'Kiingereza',
      'swahili': 'Kiswahili',
      'login_success': 'Kuingia Kukamilika',
      'register_success': 'Usajili Ukamilika',
      'login_error': 'Namba ya simu au nywila si sahihi',
      'register_error': 'Usajili ulishindikana',
      'network_error': 'Hitilafu ya mtandao',
      'retry': 'Jaribu Tena',
      'cancel': 'Ghairi',
      'confirm': 'Thibitisha',
      'ok': 'Sawa',
      'close': 'Funga',
      'search': 'Tafuta...',
      'loading': 'Inapakia...',
      'optional': 'Si lazima',
      'email': 'Barua pepe',
      'language': 'Lugha',
      'location': 'Eneo',
      'create_account': 'Fungua Akaunti',
      'login_to_continue': 'Ingia ili kuendelea',
      'confirm_logout': 'Thibitisha Kutoka',
      'confirm_logout_message': 'Una uhakika unataka kutoka?',
      'user': 'Mtumiaji',
      'full_name_required': 'Jina kamili linahitajika',
      'animal_name_required': 'Tafadhali weka jina la mnyama',
      'animal_added_success': 'Mnyama ameongezwa kikamilifu',
      'animal_add_failed': 'Imeshindwa kuongeza mnyama',
      'image_error': 'Kuna tatizo na picha',
      'name_error': 'Jina',
      'error': 'Hitilafu',
      'phone': 'Simu',
      'not_available': 'Haijapatikana',
      'full_details': 'Maelezo Kamili',
      'details': 'Maelezo',
      'basic_information': 'Taarifa za Msingi',
      'search_farmer': 'Tafuta mkulima...',
      'search_animal': 'Tafuta mnyama...',
      'try_changing_search': 'Jaribu kubadilisha search au bonyeza refresh',
      'try_changing_filter': 'Jaribu kubadilisha filter au search',
      'no_data_available': 'Hakuna data zilizopo',
      'loading_user_data': 'Inapakia taarifa za mtumiaji...',
      'confirm_delete': 'Thibitisha Kufuta',
      'confirm_delete_record': 'Una uhakika unataka kufuta rekodi hii?',
      'delete_transfer_confirm':
          'Je, una uhakika unataka kufuta rekodi hii ya uhamisho?',
      'delete_farmer_confirm':
          'Una uhakika unataka kufuta mkulima huyu? Kitendo hiki hakiwezi kutenguliwa. Wanyama wake pia watafutwa.',
      'farmer_updated': 'Mkulima amesasishwa',
      'farmer_deleted': 'Mkulima amefutwa',
      'update_failed': 'Imeshindwa kusasisha',
      'delete_failed': 'Imeshindwa kufuta',
      'transfer_deleted': 'Rekodi ya uhamisho imefutwa',
      'transfer_accepted': 'Uhamisho umekubaliwa',
      'transfer_rejected': 'Uhamisho umekataliwa',
      'request_overdue': 'Ombi limeisha muda wake',
      'last_1_day': 'Siku 1 iliyopita',
      'last_7_days': 'Siku 7 zilizopita',
      'last_14_days': 'Siku 14 zilizopita',
      'last_30_days': 'Siku 30 zilizopita',
      'days': 'siku',
      'point': 'Sehemu',
      'legend': 'Mwongozo',
      'click_marker_details': 'Bonyeza alama kuona maelezo',
      'click_to_view_map': 'Bonyeza kuona ramani',
      'animal_map': 'Ramani ya Wanyama',
      'center_on_animals': 'Weka wanyama katikati',
      'status_label': 'Hali',
      'last_seen_location': 'Mahali pa mwisho alipoonekana',
      'animal': 'Mnyama',
      'animal_number': 'Namba ya Mnyama',
      'livestock_number': 'Namba ya Mifugo',
      'type': 'Aina',
      'color': 'Rangi',
      'change_status': 'Badilisha Hali',
      'link_gps_device': 'Unganisha GPS Device',
      'history': 'Historia',
      'change_picture': 'Badilisha picha',
      'name_of_livestock': 'Jina la Mifugo',
      'type_of_livestock': 'Aina ya Mifugo',
      'save_changes': 'Hifadhi Mabadiliko',
      'edit_livestock': 'Hariri Mifugo',
      'animal_update_success': 'Maelezo ya mnyama yamesasishwa',
      'animal_update_failed': 'Imeshindwa kusasisha maelezo ya mnyama',
      'status_update_success': 'Hali imebadilishwa kikamilifu',
      'status_update_failed': 'Imeshindwa kubadilisha hali',
      'animal_delete_confirm':
          'Una uhakika unataka kufuta mnyama huyu? Kitendo hiki hakiwezi kutenguliwa.',
      'animal_deleted_success': 'Mnyama amefutwa kikamilifu',
      'recipient_not_found':
          'Mpokeaji uliyemuweka hajapatikana kwenye mfumo. Hakikisha namba ya simu ni sahihi.',
      'self_transfer_error':
          'Huwezi kuhamisha umiliki kwenda kwako mwenyewe. Weka namba ya mpokeaji tofauti.',
      'invalid_recipient_phone': 'Namba ya simu ya mpokeaji si sahihi.',
      'recipient_phone_required': 'Tafadhali weka namba ya simu ya mpokeaji',
      'request_sent_success': 'Ombi lako limetumwa kikamilifu',
      'transfer_details_upper': 'Maelezo ya Uhamisho',
      'notes_optional': 'Maelezo (Si lazima)',
      'transfer_notice': 'Mpokeaji ataarifiwa na ana siku 7 kukubali uhamisho.',
      'start_transfer': 'Anza Uhamisho',
      'phone_hint': '255XXXXXXXXX au 0XXXXXXXXX',
      'passwords_do_not_match': 'Nywila hazilingani',
      'password_min_length': 'Nywila lazima iwe na herufi 6 au zaidi',
      'registration_failed_try_again': 'Usajili ulishindikana. Jaribu tena.',
      'message_title_required': 'Tafadhali weka kichwa cha ujumbe',
      'message_required': 'Tafadhali weka ujumbe wako',
      'broadcast_success_all': 'Ujumbe umetumwa kikamilifu kwa wafugaji wote',
      'broadcast_header': 'Ujumbe kwa Wafugaji Wote',
      'broadcast_subtitle':
          'Ujumbe wako utafika kwa wafugaji wote waliosajiliwa',
      'broadcast_description':
          'Ujumbe huu utatumwa kwa wafugaji wote waliosajiliwa kwenye mfumo.',
      'message_title': 'Kichwa cha Ujumbe',
      'message_title_hint': 'Mfano: TAARIFA MUHIMU KWA WAFUGAJI',
      'your_message': 'Ujumbe Wako',
      'message_hint':
          'Andika ujumbe wako hapa...\n\nMfano: Kila mkulima atakayefika kwenye mkutano wa tarehe 15 atapata mafunzo ya kisasa ya ufugaji...',
      'message_preview': 'Muundo wa Ujumbe',
      'preview_empty': 'Muundo wa ujumbe wako utaonekana hapa',
      'send_message': 'Tuma Ujumbe',
      'broadcast_footer': 'Ujumbe utafika kwa wafugaji wote waliosajiliwa',
      'take_photo': 'Piga Picha',
      'choose_from_gallery': 'Chagua kutoka Gallery',
      'device_id_hint': 'Mfano: GPS001, GPS002, nk',
      'qr_hint': 'Skan QR code ikiwa unayo',
      'all_required_fields': 'Tafadhali jaza sehemu zote muhimu',
      'registration_success': 'Usajili wako umekamilika kikamilifu',
      'add_new_police_officer': 'Ongeza Afisa Polisi Mpya',
      'add_police_subtitle':
          'Jaza taarifa zote ili kuongeza afisa  kwenye mfumo',
      'police_added_success': 'Afisa ameongezwa kikamilifu',
      'police_add_failed': 'Imeshindwa kuongeza afisa polisi',
      'add_police_button': 'Ongeza Afisa ',
      'phone_helper': 'Mfano: 255712345678 au 0712345678',
      'all': 'Wote',
      'no_animals_found': 'Hakuna wanyama waliopatikana',
      'no_farmers_found_title': 'Hakuna wafugaji waliopatikana',
      'name_not_available': 'Jina halijapatikana',
      'phone_not_available': 'Namba haijapatikana',
      'no_animals_yet': 'Hakuna wanyama bado',
      'gps_device_required': 'Tafadhali weka Device ID',
      'device_not_found': 'Device haipo. Tafadhali wasiliana na Afisa Kilimo.',
      'gps_linked_success': 'GPS device imeunganishwa kikamilifu',
      'gps_link_failed': 'Imeshindwa kuunganisha device',
      'link_gps_title': 'Unganisha GPS Device',
      'enter_gps_device_id': 'Ingiza Device ID ya GPS tracker',
      'gps_device_help': 'Device ID inapatikana kwenye GPS tracker yako',
      'device_id_helper': 'Chagua Device ID yoyote kama GPS001, GPS002, GPS003',
      'qr_code_optional': 'QR Code (Si lazima)',
      'link_device_button': 'Unganisha Device',


      'first_name': 'Jina la Kwanza',
      'last_name': 'Jina la Mwisho',
      'middle_name': 'Jina la Kati',
      'first_name_required': 'Jina la kwanza linahitajika',
      'last_name_required': 'Jina la mwisho linahitajika',
      'first_name_min_length':
          'Jina la kwanza lazima liwe na herufi 3 au zaidi',
      'first_name_max_length': 'Jina la kwanza lazima liwe chini ya herufi 10',
      'first_name_letters_only': 'Jina la kwanza lazima liwe na herufi tu',
      'last_name_min_length': 'Jina la mwisho lazima liwe na herufi 3 au zaidi',
      'last_name_max_length': 'Jina la mwisho lazima liwe chini ya herufi 10',
      'last_name_letters_only': 'Jina la mwisho lazima liwe na herufi tu',
      'middle_name_min_length': 'Jina la kati lazima liwe na herufi 3 au zaidi',
      'middle_name_max_length': 'Jina la kati lazima liwe chini ya herufi 10',
      'middle_name_letters_only': 'Jina la kati lazima liwe na herufi tu',


      'phone_required': 'Namba ya simu inahitajika',
      'phone_invalid_format': 'Namba ya simu lazima iwe na tarakimu 9',
      'phone_invalid_network':
          'Network isiyo sahihi. Tumia Vodacom, Airtel, Tigo (yas), au Halotel',


      'location_required': 'Eneo linahitajika',
      'location_min_length': 'Eneo lazima liwe na herufi 3 au zaidi',

      'password_required': 'Nywila inahitajika',
      'password_min_length_8': 'Nywila lazima iwe na herufi 8 au zaidi',
      'password_uppercase': 'Nywila lazima iwe na angalau herufi kubwa moja',
      'password_lowercase': 'Nywila lazima iwe na angalau herufi ndogo moja',
      'password_number': 'Nywila lazima iwe na angalau namba moja',
      'password_special':
          'Nywila lazima iwe na angalau alama maalum (!@#\$%^&*(),.?":{}|<>)',


      'email_invalid': 'Tafadhali weka barua pepe sahihi',

      'confirm_password_required': 'Tafadhali thibitisha nywila yako',
      'password_min_hint': '8+ herufi: A-Z, a-z, 0-9, !@#',

      'network_vodacom': 'Vodacom',
      'network_airtel': 'Airtel',
      'network_tigo': 'Tigo (yas)',
      'network_halotel': 'Halotel',

      'farmer_dashboard': 'Dashibodi ya Mkulima',
      'officer_dashboard': 'Dashibodi ya Afisa',
      'police_dashboard': 'Dashibodi ya Polisi',
      'dashboard': 'Dashibodi',
      'habari': 'Habari',

      'law_enforcement_dashboard': 'Dashibodi ya Ulinzi na Usalama',
      'good_morning': 'Habari za Asubuhi',
      'total_cases': 'Jumla ya Kesi',
      'stolen_reported': 'Imeripotiwa Kuibwa',
      'recovered': 'Imepatikana',
      'pending': 'Inasubiri',
      'quick_actions': 'Vitendo vya Haraka',
      'report_stolen': 'Ripoti Wizi',
      'search_animal': 'Tafuta Mnyama',
      'view_map': 'Tazama Ramani',
      'recent_reports': 'Ripoti za Hivi Karibuni',
      'new': 'Mpya',
      'view_all_reports': 'Ona Ripoti Zote',
      'no_recent_reports': 'Hakuna ripoti za hivi karibuni',
      'animal_details': 'Maelezo ya Mnyama',
      'last_known_location': 'Mahali pa Mwisho',
      'latitude': 'Latitudo',
      'longitude': 'Longitudo',
      'view_on_map': 'Tazama kwenye Ramani',
      'stolen': 'Imeibwa',
      'reported_on': 'Iliripotiwa Tarehe',
      'owner': 'Mmiliki',
      'animal_id': 'Namba ya Mnyama',

      'total_animals': 'Jumla ya Wanyama',
      'active_gps': 'GPS Hai',
      'unread_alerts': 'Arifa Hazijasomwa',
      'stolen_animals': 'Wanyama Walioibwa',
      'stolen_animals_reported': 'Wanyama Walioripotiwa Kuibwa',
      'stolen_animals_list': 'Orodha ya Wanyama Walioibwa',
      'no_stolen_animals': 'Hakuna wanyama walioripotiwa kuibwa',
      'total_farmers': 'Jumla ya Wafugaji',
      'view_all': 'Ona Yote',

      'my_animals': 'Wanyama Wangu',
      'all_animals': 'Wanyama Wote',
      'add_animal': 'Ongeza Mnyama',
      'animal_name': 'Jina la Mnyama',
      'animal_type': 'Aina ya Mnyama',
      'animal_color': 'Rangi',
      'cattle': 'Ng\'ombe',
      'goat': 'Mbuzi',
      'sheep': 'Kondoo',
      'other': 'Nyingine',
      'add_photo': 'Ongeza Picha',
      'notes': 'Maelezo',
      'animal_id': 'Namba ya Mnyama',
      'owner': 'Mmiliki',
      'status': 'Hali',
      'update_status': 'Badilisha Hali',
      'active': 'Hai',
      'sold': 'Imeuzwa',
      'slaughtered': 'Imechinjwa',
      'dead': 'Imekufa',
      'stolen': 'Imeibwa',
      'no_animals': 'Hakuna wanyama',
      'animals': 'Wanyama',
      'mark_as_active': 'Weka kama Hai',
      'mark_as_sold': 'Weka kama Ameuzwa',
      'mark_as_slaughtered': 'Weka kama Amechinjwa',
      'mark_as_dead': 'Weka kama Amekufa',
      'report_as_stolen': 'Ripoti kama Ameibwa',

      'location_history': 'Historia ya Mahali',
      'view_on_map': 'Tazama kwenye Ramani',
      'no_location_data': 'Hakuna data za mahali',
      'no_location_data_for_animal': 'Hakuna data za mahali kwa mnyama huyu',
      'location_points': 'Sehemu Alizopitia',
      'start': 'Mwanzo',
      'current': 'Sasa',
      'center_on_map': 'Weka Katikati',
      'last_seen': 'Ilionekana Mwisho',
      'speed': 'Kasi',
      'reported_on': 'Iliripotiwa Tarehe',
      'open_in_maps': 'Fungua kwenye Ramani',

      'transfer_ownership': 'Hamisha Umiliki',
      'transfer_requests': 'Maombi ya Uhamisho',
      'transfer_details': 'Maelezo ya Uhamisho',
      'recipient_phone_number': 'Namba ya Simu ya Mpokeaji',
      'initiate_transfer': 'Anzisha Uhamisho',
      'transfer_info': 'Mpokeaji atakuwa na siku 7 kukubali uhamisho huu',
      'transfer_initiated_success': 'Ombi la uhamisho limetumwa',
      'transfer_failed': 'Imeshindwa kutuma ombi la uhamisho',
      'no_transfers': 'Hakuna historia ya uhamisho',
      'from': 'Kutoka',
      'to': 'Kwenda',
      'initiated_at': 'Iliyoanzishwa',
      'confirmed_at': 'Iliyokubaliwa',
      'pending': 'Inasubiri',
      'confirmed': 'Imekubaliwa',
      'rejected': 'Imekataliwa',
      'expired': 'Imeisha',
      'accept': 'Kubali',
      'reject': 'Kataa',
      'delete_record': 'Futa Rekodi',

      'alerts': 'Arifa',
      'all_alerts': 'Arifa Zote',
      'no_alerts': 'Hakuna arifa',
      'mark_as_read': 'Weka kama Imesomwa',
      'theft_alert': 'Arifa ya Wizi',
      'lost_animal_alert': 'Arifa ya Mnyama Aliyepotea',
      'general_alert': 'Arifa ya Jumla',
      'new_alerts': 'Arifa Mpya',
      'proximity_alarm_title': 'Alarm ya umbali wa mnyama',
      'proximity_alarm_attention': 'Alarm ya umbali inahitaji ruhusa',
      'proximity_alarm_message': 'Wanyama hawa wamezidiana zaidi ya mita 5:',
      'proximity_alarm_location_problem':
          'Washa intaneti ili kutumia alarm ya umbali wa wanyama.',
      'stop_alarm': 'Zima alarm',

    
      'reports': 'Ripoti',
      'generate_report': 'Tengeneza Ripoti',
      'population_report': 'Ripoti ya Idadi',
      'generate_population_report_desc':
          'Tengeneza ripoti inayoonyesha idadi ya wanyama kwa aina na hali',
      'report_results': 'Matokeo ya Ripoti',
      'report_generated_success': 'Ripoti imetengenezwa kikamilifu',
      'report_generate_failed': 'Imeshindwa kutengeneza ripoti',
      'animals_by_type': 'Wanyama kwa Aina',
      'animals_by_status': 'Wanyama kwa Hali',
      'generated_at': 'Imetengenezwa',

   
      'send_broadcast': 'Tuma Ujumbe',
      'broadcast_info': 'Ujumbe huu utatumwa kwa wakulima wote waliosajiliwa',
      'title': 'Kichwa',
      'message': 'Ujumbe',
      'preview': 'Muundo',
      'broadcast_sent_successfully': 'Ujumbe umetumwa kikamilifu',
      'broadcast_failed': 'Imeshindwa kutuma ujumbe',

      // ========== FARMERS LIST ==========
      'farmers': 'Wafugaji',
      'farmers_list': 'Orodha ya Wafugaji',
      'no_farmers_found': 'Hakuna wafugaji waliopatikana',
      'edit_farmer': 'Hariri wafugaji',
      'delete_farmer': 'Futa wafugaji',
      'farmer_details': 'Maelezo ya wafugaji',
      'joined': 'Alijiunga',
      'joined_date': 'Tarehe ya Kujiunga',
      'role': 'Wadhifa',
      'basic_info': 'Taarifa za Msingi',
      'animals_count': 'Wanyama',

      // ========== PROFILE ==========
      'profile': 'Wasifu',
      'my_profile': 'Wasifu Wangu',
      'settings': 'Mipangilio',

      // ========== POLICE ==========
      'theft_alerts': 'Arifa za Wizi',
      'add_police': 'Ongeza Afisa Polisi',
      'police_officer': 'Afisa Polisi',
      'work_location': 'Eneo la Kazi',
      'police': 'Polisi',

      // ========== ACTIVITY LOG ==========
      'activity_log': 'Rekodi ya Shughuli',
      'no_logs_found': 'Hakuna rekodi zilizopatikana',
      'activity_type': 'Aina ya Shughuli',
      'description': 'Maelezo',
      'timestamp': 'Muda',

      // ========== DRAWER MENU ==========
      'my_animals_menu': 'Wanyama Wangu',
      'add_animal_menu': 'Ongeza Mnyama',
      'transfer_requests_menu': 'Maombi ya Uhamisho',
      'alerts_menu': 'Arifa',
      'farmers_menu': 'Wafugaji',
      'all_animals_menu': 'Wanyama Wote',
      'broadcast_menu': 'Tuma Ujumbe',
      'reports_menu': 'Ripoti',
      'activity_log_menu': 'Rekodi ya Shughuli',
      'police_menu': 'Polisi',
      'stolen_animals_menu': 'Wanyama Walioibwa',
      'theft_alerts_menu': 'Arifa za Wizi',
      'profile_menu': 'Wasifu Wangu',
      'logout_menu': 'Toka',

      // ========== BUTTONS ==========
      'save': 'Hifadhi',
      'edit': 'Hariri',
      'delete': 'Futa',
      'update': 'Sasisha',
      'refresh': 'Burudisha',
      'back': 'Rudi',
      'next': 'Endelea',
      'submit': 'Wasilisha',
      'continue': 'Endelea',
    },
  };

  LanguageService() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final savedLanguageCode = prefs.getString(AppConstants.languageKey);
    final languageCode = _translations.containsKey(savedLanguageCode)
        ? savedLanguageCode!
        : defaultLanguageCode;
    _currentLocale = Locale(languageCode);
    print('🌐 Language loaded: $languageCode');
    notifyListeners();
  }

  Future<void> setLanguage(String languageCode) async {
    if (!_translations.containsKey(languageCode)) {
      languageCode = defaultLanguageCode;
    }
    print('🌐 Setting language to: $languageCode');
    _currentLocale = Locale(languageCode);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(AppConstants.languageKey, languageCode);
    notifyListeners();
    print('🌐 Language changed to: $languageCode, listeners notified');
  }

  String translate(String key) {
    final normalizedKey = _normalizeKey(key);
    return _translations[_currentLocale.languageCode]?[normalizedKey] ??
        _translations['en']?[normalizedKey] ??
        key;
  }

  String _normalizeKey(String key) {
    const aliases = {
      'Addres': 'address',
      'create account': 'create_account',
      'login to continue': 'login_to_continue',
      'view all': 'view_all',
      'View All': 'view_all',
      'Stolen Animals Reported': 'stolen_animals_reported',
      'Stolen Animals List': 'stolen_animals_list',
      'No Stolen Animals Found': 'no_stolen_animals',
    };

    return aliases[key] ?? key;
  }
}

extension Translate on BuildContext {
  String tr(String key) {
    final languageService = Provider.of<LanguageService>(this, listen: false);
    return languageService.translate(key);
  }
}
